nguage: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux
env:
  global:
    - MAKEFLAGS="-j 6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
notifications:
  email:
    - xorz57@gmail.com
install:
  - sudo pip install codecov
script:
  - bash build_tests.sh
  - bash run_tests.sh
after_success:
  - cd tests && codecov