nguage: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo pip install codecov
script:
  - bash build_tests.sh
  - bash run_tests.sh
  - cd tests && codecov
env:
  global:
    - MAKEFLAGS="-j 6"
notifications:
  email:
    - xorz57@gmail.com